### ISSUE TITLE
ROM Porting has Failed

### ISSUE THREAD

**Issue by Emman0289** [moonblade/workdir-rom-porter#2]
I was porting MIUI for my Huawei device, everything goes smoothly until... ROM Porting has failed. 

[LOG-10639.txt](https://github.com/moonblade/Rom-Porter/files/12712765/LOG-10639.txt)

**Comment by Emman0289** [comment]
I'm using Redmi Note 5a or Redmi Y1 for the port ROM (MIUI 11.0.2.0) , and i use the Huawei Y7 Prime 2017 Stock ROM (EMUI 5.1.3).

They are basically the same specs to eachother.

**Comment by moonblade** [comment]
This repo isn't active and hasn't been worked on since android kitkat, its pretty much severely out of date.
